{% set name = "llama-parse" %}
{% set version = "0.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/llama_parse-{{ version }}.tar.gz
  sha256: b2a29dbce32b99342fb942d1c210abef0eea57df6f26666299039ef7a931feff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.1,<4.0
    - llama-index-core >=0.11.0

test:
  imports:
    - llama_parse
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Parse files into RAG-Optimized formats.
  home: https://github.com/run-llama/llama_parse
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
    - jan-janssen
