{% set name = "llama-parse" %}
{% set version = "0.6.79" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_parse-{{ version }}.tar.gz
  sha256: 413dad376e0652190a3c0ce3c7d2080559ee7d6dbcc81295c3970c66f13c07b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - llama-cloud-services >=0.6.79
    - pydantic !=2.10
    - click >=8.1.7,<9.0.0
    - python >={{ python_min }},<4.0
    - llama-index-core >=0.11.0

test:
  imports:
    - llama_parse
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Parse files into RAG-Optimized formats.
  home: https://github.com/run-llama/llama_parse
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
    - jan-janssen
