{% set name = "llama-parse" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/llama_parse-{{ version }}.tar.gz
  sha256: 9e6a6f80da1185d8b23a96ff3141a154a833003f8ea9c546601c68b2bbe424e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.1,<4.0
    - llama-index-core >=0.10.29

test:
  imports:
    - llama_parse
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Parse files into RAG-Optimized formats.
  home: https://github.com/run-llama/llama_parse
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
    - jan-janssen
